### ISSUE TITLE
Define Prisma Schemas for Database Models

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#1]
### Background:
In order to establish a robust foundation for the quiz-hosting application, the initial step is to **define the Prisma schemas** for the core database models. These models, namely **User, Room, Question, and Option**, form the backbone of the application's data architecture.

### Objective:
The goal of this issue is to create precise and comprehensive Prisma schemas that accurately represent the structure of the User, Room, Question, and Option entities within the database given the attributes of each model. Prisma schemas act as a bridge between the application code and the database, facilitating seamless communication and interaction.

### Fields/Attributes for each model:
Each attribute in each model may have some description of what it's purpose is. Some fields may not have a DataType defined, because it may be obvious or intuitive.

  - **User Model:**
1. name
2. email (unique)
3. password
4. currPoints (default 0)

  - **Question Model:**
1. question
2. options: ( Options[] ) (**NOTE**: the @relation should look something like this: @relation(..., onDelete: Cascade)
(the onDelete: Cascade option allows deleting records that are related to one another. In this case, every Question is related to an array of Options, and vice-verse. Deleting a question would delete all the related Options as well, using onDelete.)
3. correctOption (Option)
4. correctOptionId (referenced by correctOption to the Option record's id)

  - **Option Model:**
1. question (Question)
2. questionId (referenced by question to the Question record's id)
3. option

  - **Room Model:**
1. code (unique, string)
2. Questions[] (question, options, and correct option = one question) (add onDelete: Cascade) (now, deleting a Room would delete all the related Questions, which would in turn delete all the associated Options)
3. Users[] (connected users to the room)

These models should be created in the prisma/schema.prisma file. Once the schemas seem right, you will be told to migrate the schema. Once the migration is successful, you will receive **30 points**
This is a **First-Come-First-Serve** issue. For more details, read the Participant's Rulebook uploaded on Discord.

Happy contributing!

**Comment by bhupesh98** [comment]
@criticic Assigned!

**Comment by PranavBansal21** [comment]
claim

**Comment by Rudreshdabre12** [comment]
claim

**Comment by VatsalBhuva11** [comment]
Schemas written perfectly, with the necessary relations made. Congrats, @criticic !

**Comment by vineeshmittal1** [comment]
claim
