### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#12]
1) Create a `JWT` when the user is signed in and send that token also as part of the response (so that you can use it for further requests) (in `userAuth.controllers.js`), with the payload data including:
> - **id** : userId of the logged in User
> - **isCreator**: false by default, since when a User is logged in, there's no room created by that User
> - **name**: name of the User

2) Update the `userAuth.middleware.js` file to ensure that the `req.user` object contains the fields mentioned above (i.e., make changes to the `req.user = data.user` line based on the changes in the above point).
Also, create a `.env` variable called `JWT_SECRET`, and assign it a random valid string. Use this variable instead of the 'grepit-backend' secret used. Add the variable in `.env.example` file as well.

3) Update the `room.controller.js` file to ensure that when a User creates a room successfully, the `req.user` object for that user reflects the change by setting the `isCreator` field to `true`.

4) If I may have missed out on some other related changes, please feel free to get them cleared. Since there may be changes required in other parts of the file as well, this issue is marked as **competitive**. Multiple PRs may be submitted, and the one that accounts for all the changes will be accepted.

**Comment by rnavaneeth992** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
There's no need to claim this.
Fork the repo (and star it if you like it :) ), make the changes, open a PR.
The best PR by the EOD 16th December will be accepted.

**Comment by VatsalBhuva11** [comment]
If anyone is found copying the PR of someone else, you may receive points deduction and in the worst case, a disqualification,
