### ISSUE TITLE
Adventurer's Gateway

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Backend#17]
Develop the pathway for adventurers to join the realm using room codes. 

## Description:
- Extract Room Code from URL which will be given as a query key-value pair.
- Retrieve the room code from the query parameters of the URL.
- Check if the room code is valid (exists, is active, etc.). If not, handle the error appropriately.
- Ensure that the user is authenticated before allowing them to join the room. If not authenticated, redirect them to the login page or prompt them to sign in. Use the middleware for this, bug fixes for the middleware are undergoing, it'll be merged by tonight as it is a competitive issue. You can just add the middleware and leave the rest.
- If the user is authenticated and the room code is valid, register the user in the database as a participant in the specified room.
- Provide feedback to the user about the success or failure of the join operation. This could be in the form of a success message or an error message.

>[!Note]
> This controller function is broken down in parts as it requires socket.io library, more issues will be posted as soon as it is complete.

## File Location:
`src/controllers/room.controllers.js`.

We'll be implementing websockets using socket.io library where actual room will be created for seamless interaction.
Stay tuned, the task will be posted soon.

Claim this Issue to work on this!
I will be super happy 😊 if you give our repo a ⭐.
In case of further clarification ping @GrepIt-Backend on our discord channel.

**Comment by criticic** [comment]
claim

**Comment by kushal7201** [comment]
claim

**Comment by captainflatbelly** [comment]
claim

**Comment by PranavBansal21** [comment]
Claim

**Comment by Jarviss77** [comment]
claim

**Comment by bhupesh98** [comment]
@criticic Assigned!
