### ISSUE TITLE
Upgrading to WebSockets!

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Backend#20]
Users will enter the immersive world of our upgraded system, traversing the technological landscape as they seamlessly transition from the traditional HTTP server to the dynamic realm of WebSockets. The primary objective is to introduce a room creation feature, complete with a unique code or URL for user interaction. Additionally, users entering the system without the 'schedule' query parameter should receive a personalized message informing them of its absence.

**_Task:_**
Upgrade the current HTTP server to leverage WebSockets for enhanced real-time communication. Implement a controller to facilitate room creation, generating a unique code or URL for user access. Provide a tailored message for users entering without the 'schedule' query parameter.

**_Details:_**
Controller:
Modify a controller function, perhaps named createRoom, responsible for orchestrating the creation of rooms using WebSockets. Ensure seamless integration within the existing codebase.

**_Unique Code/invite URL:_**
Generate a unique code or invite URL for each created room, ensuring its exclusivity. This identifier will serve as the entry point for users to join the room.

**_User Entry Without 'schedule' Query Param:_**
Implement logic to handle user entry without the 'schedule' query parameter. Craft a user-friendly message explaining the necessity of the 'schedule' parameter and guide users on its inclusion.

**_Response:_**
Craft appropriate responses for successful room creation, invalid parameters, and missing 'schedule' query parameter. Ensure clear communication with users through meaningful status codes and messages.

**_Database Interaction:_**
Modify the database interactions to accommodate room-related data. Ensure proper storage and retrieval of room information.

Claim this Issue and don't forget to give our repository a star! Exciting enhancements, including the integration of WebSockets, are on the horizon. Stay tuned for future updates. If you encounter any confusion or need additional resources, feel free to ping me on Discord.

*PS:* This task requires time and learning websockets extensively, so it is recommended to read the whole thing and discuss with @bhupesh98 or @VatsalBhuva11 regarding any confusion here before claiming the task. A PR for this task is not expected very soon.

**Comment by Rohit-110** [comment]
claim

**Comment by Piyush-Raj-Tiwari** [comment]
Claim

**Comment by bhupesh98** [comment]
> claim

Have you read the whole paragraph and are u ready for the learning process for this task and clear about what to do and have a rough idea about how to do it?

**Comment by DikshantK2004** [comment]
Claim

**Comment by bhupesh98** [comment]
Anyone who knows about websocket connection or have prior experience in web development can describe themselves.
Actually this task is not meant for beginners in backend development, so a basic conversation regarding the task is necessary before assigning him/her

**Comment by DikshantK2004** [comment]
What is the schedule query parameter? Is it the time when the quiz takes place? 
I have also worked with sockets in python for peer to peer file sharing

**Comment by criticic** [comment]
Previous Experience: Have worked with socket-io and all to like make a chat app from a tutorial

some questions, `Unique Code/invite URL:
Generate a unique code or invite URL for each created room, ensuring its exclusivity. This identifier will serve as the entry point for users to join the room.` is this different from roomCode

`User Entry Without 'schedule' Query Param:
Implement logic to handle user entry without the 'schedule' query parameter. Craft a user-friendly message explaining the necessity of the 'schedule' parameter and guide users on its inclusion.` is this like a time when room will be active?

**Comment by bhupesh98** [comment]
> What is the schedule query parameter? Is it the time when the quiz takes place? 
> I have also worked with sockets in python for peer to peer file sharing

Yes, we are thinking of a scheduled quiz competition but that part can be implemented later if found to be too time taking, as we are first prioritising functionality over features.

As you asked for the claim first, I am assigning the task to you. Do ping mentors on discord regarding any confusion/clarification.

**Comment by bhupesh98** [comment]
> Previous Experience: Have worked with socket-io and all to like make a chat app from a tutorial
> 
> some questions, `Unique Code/invite URL:
> Generate a unique code or invite URL for each created room, ensuring its exclusivity. This identifier will serve as the entry point for users to join the room.` is this different from roomCode
> 
> `User Entry Without 'schedule' Query Param:
> Implement logic to handle user entry without the 'schedule' query parameter. Craft a user-friendly message explaining the necessity of the 'schedule' parameter and guide users on its inclusion.` is this like a time when room will be active?

That is the same thing but we broke the functionalities of the controller as the task was getting bigger.
Yes, that will be the time when room gets active, till then we'll just save the records.

**Comment by VatsalBhuva11** [comment]
@DikshantK2004 very well done for writing the core logic of the sockets part!
