### ISSUE TITLE
Code fixes

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#21]
Small fixes;
- Only the room's creator should be able to update the room name and description, and remove other users from the room
- Hence, create a separate controller to allow a **logged in** user to disconnect themselves (route should be `/api/v1/room/user/disconnect`
- Also change the `/api/v1/room/user/delete` route to `/api/v1/room/user/remove` for better semantics (explains the action of one person, here the room creator, removing someone and not deleting them).
It's not competitive, as it's quite easy

**Comment by criticic** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@criticic assigned

**Comment by VatsalBhuva11** [comment]
@criticic quick work! well done.

**Comment by VatsalBhuva11** [comment]
i will add your points manually. sorry, forgot to assign you
