### ISSUE TITLE
Transferring Ownership!

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#23]
The creator is tired of maintaining his fellowmates and serving as the sole knowledge-able person in that room. He wishes to transfer the ownership to another person in that room. Also when the user leaves, randomly assign another user in that room as the creator, making necessary changes elsewhere in the models (like setting the isCreator for that user to false, and isCreator for that random user to true).

Handle both these cases: one, when the owner manually chooses who to give the ownership (`/api/v1/room/transferOwner`), and another when the owner leaves the room (controller already exists, `/api/v1/room/disconnect`). The second controller should be modified to randomly assign another User as the creator.

**Comment by criticic** [comment]
claim

**Comment by WadadParker** [comment]
claim

**Comment by PranavBansal21** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
@criticic assigned!

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
good job @criticic !
