### ISSUE TITLE
The Room shall cease to exist

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#24]
Alas! The knowledge pool has exhausted in the Realm, and the creator decides to vanish the room, banishing all the existing members!
Forge a controller, on the `/api/v1/room/delete` route, to delete a room and ensuring that the related questions and options are also deleted (or have we already handled that in the schema?)
It is also required to handle the sockets appropriately. Deleting a room requires disconnecting all the sockets associated with that room. Assume that the sockets exist in a socket-room having the name as the `code` of that room. Update the related models as required whenever a room is deleted, ensuring data integrity.
The other connected users in that room would automatically get disconnected from the room by this action, so would we require a `socket event` to be emitted for handling this, to make necessary changes in the client-side for each socket? Let us know your approach either in discord, or pinging us here (@VatsalBhuva11 and @bhupesh98 ).

**Comment by criticic** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
@criticic you're already assigned one issue at the moment. Hence, assigning this to @kushal7201

**Comment by WadadParker** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
@kushal7201 you're already assigned 3 issues. Hence, you cannot be assigned any more issues till you're done with atleast one other issue across OpenCode.

**Comment by VatsalBhuva11** [comment]
Since @Jarviss77 got assigned #25 , this is being transferred to @WadadParker

**Comment by VatsalBhuva11** [comment]
@WadadParker how's the progress?

**Comment by VatsalBhuva11** [comment]
@WadadParker  i need a response from you by 10am IST, 19th Dec. Failing to do so would cause this issue to be up-for-grabs again.

**Comment by WadadParker** [comment]
Hello, am working on it, I'll raise a PR in some time. I was occupied with other thing so did not respond soon. But rest assured the work will be done

**Comment by VatsalBhuva11** [comment]
very well done @WadadParker !
