### ISSUE TITLE
Announcements!

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#25]
📢 The quiz will be starting shortly
📢 Congrats, @johndoe for finishing on top of the leaderboard!

We require such a way for the creator to announce to all other users about certain events. Craft a controller to allow the creator to make announcements, which should be handled using sockets and emitted to all the other connected sockets of that room. Assume that the sockets are joined in a socket-room named by the `code` of that room.
Unleash the controller on the `/api/v1/room/announce` endpoint! Update the `API_ENDPOINTS.md` file accordingly!

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
Claim

**Comment by ssugam10** [comment]
claim

**Comment by WadadParker** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
@Jarviss77 assigned to you, as @kushal7201 is already assigned the previous issue.

**Comment by VatsalBhuva11** [comment]
@Jarviss77 how's the progress?

**Comment by VatsalBhuva11** [comment]
@Jarviss77 i need a response from you by 10am IST, 19th Dec. Failing to do so would cause this issue to be up-for-grabs again.

**Comment by Jarviss77** [comment]
On it
