### ISSUE TITLE
Invite-only rooms

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#27]
An incredible number of users are joining my room!!!
Where's the privacy???
Let's solve this by giving an option to the room-creator to make the room invite-only.

Just like an open room, an invite-only room will also have a code associated to it. Others can use this code to join this room. But here's the difference. In an open room, the attempting user will directly be added to the room. But in an invite-only room, the creator **must accept/reject** the **pending** users in the waiting list.
This would require the addition of
1. `pending` field (default should be an empty array of Users)
2. `isInviteOnly` field (bool, default false)

Now, the `addUserToRoom` controller should be modified. When the room is **NOT** inviteOnly, the normal behaviour is expected: anyone can join the room.
But if the room is inviteOnly, any user attempting to join the room will first be placed in the pending list.

Another controller should be created (under `/api/v1/room/user/pending`, which accepts a query param of either `accept` or `reject`, and another query param which is the `userId` of the user to accept/reject). Based on the query param, the pending user will either be moved to the `Users` list of that room, or removed from the Pending list. Note that this action can only be done by the room's creator.

Do not include sockets for now, as it would be upgraded once the main sockets implementation for Room Creation/Joining is implemented in #20.

It is necessary to upgrade the schema for this task, so **get the schema confirmed** once before running `npx prisma db push`. It is also required to update the `API_ENDPOINTS.md` file as part of this task

**Comment by criticic** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by captainflatbelly** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@criticic assigned to you!

**Comment by VatsalBhuva11** [comment]
good job, @criticic !
