### ISSUE TITLE
Forge Your Identity

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#3]
At the Registration Station, users create their quiz identities by choosing a username and providing an email and a password.

In this task, you are required to write necessary controllers (in **src/controllers/userAuth.controllers.js**) receiving the necessary Form Input (username, email, and password). Encrypt the password using **bcrypt**, using **10 salt rounds**. The controller should be run on the **/api/v1/auth/register** route, which should be modified in the **src/routes/v1/userAuth.routes.js**

Having made secure the identity of the user, add them to the realm of the users, by adding them to the User model, displaying a success message and giving the user an entry to the Realm of Quizventure!

**NOTE:** The DATABASE_URL for the database hosted on PlanetScale is available in the #grepit-backend channel on discord. Use this value and add it in your **.env** file. Please do not commit the URL, or your PR will not be merged (for security reasons)

**Comment by Apoorv012** [comment]
claim

**Comment by PranavBansal21** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@Apoorv012 assigned!

**Comment by Nandinig24** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
@Apoorv012 
1) ensure that relations are handled appropriately without any conflicts between the models. assume the frontend sends the username, email, and password as form data. 
2) once the user is successfully created, send a 200 status code, with the data as the newly created user.
3) also, create a "Test" user using Postman, with the following fields: username: "test", password: "test", email: "test@gmail.com". Upload the screenshot of the Test user being created successfully (i.e., the message logged upon creating the test user.)
4) once done, submit a PR.

react with a thumbs up if you've read this comment.

**Comment by parimal-10** [comment]
claim

**Comment by vineeshmittal1** [comment]
claim
