### ISSUE TITLE
Leaderboard Unveiling

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#33]
As the last question's timer runs out, the leaderboard shines forth, showcasing the champions of the quizventure.

The leaderboard should send the data in a **descending (higher to lower)** order of points of the Users in that room. The data sent should include:
1) Points of the user for that quiz
2) Name of the user

After the last question in that room, send an additional event called `quiz over`, with the leaderboard as the data. The clients will then listen to this event, and display the leaderboard accordingly.

**Comment by rnavaneeth992** [comment]
Claim

**Comment by Jarviss77** [comment]
Claim

**Comment by PranavBansal21** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@rnavaneeth992 assigned to you!

**Comment by VatsalBhuva11** [comment]
this issue is made of 15 points instead of 20 as the socket part is not going to be handled in this issue. it's being handled in another issue, which effectively makes this just a controller writing task.

**Comment by VatsalBhuva11** [comment]
well done, @rnavaneeth992 ! :+1:
