### ISSUE TITLE
Post Quiz Ritual

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#34]
The quiz is over and the leaderboard displayed.
While some are satisfied with their skills, some are upset of not getting the podium positions.
They discuss in a `chat-room`, available only when the quiz ends.

Set-up a feature where the connected sockets are able to chat through a **chat-room** just for that particular room. The messages of all the users in the room must be stored in the `room` model, which requires the construction of another field (in the Room model) and model for `messages`.

Ensure relevant naming of the socket events. When a client emits the `send message` event, the message should be captured on the server, and stored in the relevant room's messages field. Assume that the necessary data is available in the event's data. The messages array (each message should contain `sender's name`, `sender's Id`, and `message`) should then be emitted back to **all** the users of that room, for displaying on all the clients pages. Name the event appropriately.

Since this task requires `schema.prisma` to be changed, please get the `messages` schema verified once before running `npx prisma db push`.

Some fields in the messages schema would be: sender (User), room (Room), message (String). Add/remove any field if necessary, but do discuss it out with us once.

**NOTE: we would require a video demo for this task demonstrating the chat-room. Without the video, your PR will not get merged. Make use of the `admin.html` and `user.html` files for this, modifying them as required.**

**Comment by kushal7201** [comment]
Claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by Jarviss77** [comment]
Claim

**Comment by chiragmalik2612** [comment]
claim

**Comment by PranavBansal21** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@kushal7201 assigned

**Comment by kushal7201** [comment]
@VatsalBhuva11  I'm unable to complete the task due to lack of knowledege. Could you please unassign me from the issue?

**Comment by VatsalBhuva11** [comment]
ok sure
this issue is up for grabs again! first one to comment claim will be assigned this issue.

**Comment by Apoorv012** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@Apoorv012 assigned to you!

**Comment by Jarviss77** [comment]
claim

**Comment by DikshantK2004** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@Apoorv012 how's it going?

**Comment by Apoorv012** [comment]
Just started out

**Comment by Apoorv012** [comment]
I have completed the code, and it is working fine on the database side.
But I am not able to get the result by logging in the console, or making a window.alert()

**Comment by VatsalBhuva11** [comment]
It's alright, make a PR, we'll suggest you if any changes are needed. As long as the DB works well, it's okay. Frontend part is just for testing

**Comment by VatsalBhuva11** [comment]
> I have completed the code, and it is working fine on the database side. But I am not able to get the result by logging in the console, or making a window.alert()

It's alright, make a PR, we'll suggest you if any changes are needed. As long as the DB works well, it's okay. Frontend part is just for testing

**Comment by VatsalBhuva11** [comment]
Also it's been more than 2 days since we assigned this task... but we allowed additional time as both the mentors are currently out of town. This issue will be closed by tomorrow evening once we review the PR by tomorrow morning.

**Comment by Apoorv012** [comment]
Actually the issue that led to the delay of the PR, was not being able to check it using frontend. 🥲

**Comment by VatsalBhuva11** [comment]
> Actually the issue that led to the delay of the PR, was not being able to check it using frontend. 🥲

Yeah I saw your messages on discord, which is why I didn't force you into making a PR asap as you were already done with the task but couldn't get the frontend done which isn't that important anyway

**Comment by Apoorv012** [comment]
Thank you for understanding! :)

**Comment by VatsalBhuva11** [comment]
Good job, @Apoorv012 🌟
