### ISSUE TITLE
Unlocking the Portal

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#4]
Users step through the grand Gateway, entering the heart of the quiz realm as they successfully log in.

Task: Implement user-login functionality, by adding suitable controllers in **src/controllers/userAuth.controllers.js**. Pave a route (not so literally) for allowing the user to get through the Gateway (**/api/v1/auth/login**), mesmerizing them as they enter this beautiful and otherworldly (quite literally) realm of Quizzes.

The user will provide their username and password, which should match appropriately with their record in the database. Proper error-handling must be ensured.

Ensure that you verify the encrypted password stored in the database, and if successfully verified, should return a 200 status code with a "Successfully logged in" message. Craft a similar failure message.

**Comment by Apoorv012** [comment]
claim

**Comment by Nandinig24** [comment]
Claim

**Comment by PranavBansal21** [comment]
claim

**Comment by CodinJack** [comment]
claim

**Comment by parimal-10** [comment]
claim

**Comment by coderatiiita** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@Nandinig24 assigned to you, as @Apoorv012 is already working on a registration issue which is very similar to this task. Sorry for the inconvenience, Apoorv. This is only for this task. Generally, you will be allowed to work on multiple tasks of the same repo.

**Comment by Apoorv012** [comment]
@VatsalBhuva11 Ok, no problem

**Comment by parimal-10** [comment]
claim

**Comment by vineeshmittal1** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@Nandinig24 updates?

**Comment by DikshantK2004** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@Nandinig24 please respond, how is the task moving about?

**Comment by Nandinig24** [comment]
sorry for late reply !doing with it but facing some difficulty

**Comment by VatsalBhuva11** [comment]
ok np. please get your doubts clarified so that we can progress accordingly.

**Comment by Nandinig24** [comment]
please unaassign me task

**Comment by VatsalBhuva11** [comment]
@criticic assigned!
