### ISSUE TITLE
Migrating from roomId to roomCode

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#42]
Hola! We're back with another small issue, sorry for the delay :(. The mentors were busy with an event organised by the Mayor of the Quizventure!
To make all the controllers uniform across the project, and make the URLs more elegant, we require migrating from the usage of `roomId` to `roomCode` in those controllers which are getting the `roomId` as a query param instead of the roomCode.
If it wasn't obvious, you are also to make necessary changes to the controllers and make sure they work as before. This shouldn't be a problem, as the roomCode, like the roomId, is unique.

**Comment by chiragmalik2612** [comment]
c

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
claim

**Comment by WadadParker** [comment]
claim

**Comment by Apoorv012** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@kushal7201 assigned

**Comment by Mannxxx** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
This issue is open again! First person to "claim" it will be assigned this issue.

**Comment by WadadParker** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@WadadParker assigned to you

**Comment by VatsalBhuva11** [comment]
this issue is open for claims again!

**Comment by Jarviss77** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
@Jarviss77 already assigned #46 . next person to claim this will be assigned this issue.

**Comment by TheDivineAurora** [comment]
claim

**Comment by VatsalBhuva11** [comment]
> claim

will be assigned to you within an hour if noone else claims this, since you're already assigned 3 issues at the moment.

**Comment by TheDivineAurora** [comment]
iam only assigned 2
prs accepted but did not unassign ig

**Comment by chiragmalik2612** [comment]
claim

**Comment by Apoorv012** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
ok, assigned to @TheDivineAurora

**Comment by VatsalBhuva11** [comment]
@TheDivineAurora status?

**Comment by TheDivineAurora** [comment]
working on it give me time till night

**Comment by VatsalBhuva11** [comment]
good job, @TheDivineAurora ! :)
