### ISSUE TITLE
Sockets!

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#43]
With most of the logic part done for the sockets, the Mayor of the Quizventure has demanded thy workers to **enlist** the socket events used throughout the project, and explain briefly the use of each socket event.
It is also required to enlist the events that we've assumed would be emitted by the client, apart from the events that would be emitted by the server.
The client-side socket events can be obtained from the `html` files in the `sockets-test/` folder. The server-side socket events can be obtained by reading the backend code. It is important to provide a brief as to what each event is for, and how it's handled.
The documentation should be done in a `SOCKET_EVENTS.md` file.

**Comment by Apoorv012** [comment]
claim

**Comment by Jarviss77** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
@Apoorv012 assigned to you!

**Comment by VatsalBhuva11** [comment]
Well documented, @Apoorv012 ! :)
