### ISSUE TITLE
No more room deletion!

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#46]
In V2, we'd allow the knowledge-seekers to learn from their mistakes.
This task requires you to modify the appropriate controllers handling room deletion, such that the rooms do not get deleted when the room becomes empty. Instead, add a new field to the `Room` Schema, called `isClosed (default: false)`. When the room gets empty, set the isClosed to true.
The use of this field is that, users cannot join rooms having `isClosed` set to true, requiring a modification in the controller handling the `joinRoom` functionality. 

The `deleteRoom` controller should also be modified such that the room does not get deleted from the DB; instead it just disconnects every connected User from that room (including the creator), and set the isClosed option to true.

Make necessary changes in the `disconnectUserFromRoom`, `removeUserFromRoom` and any other controllers to stay in sync with this logic, making comments wherever necessary.

**Note: make a PR to the `v2` branch of this repo.**

**Comment by Jarviss77** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
@Jarviss77 assigned to you

**Comment by VatsalBhuva11** [comment]
all the required changes done, well done!
