### ISSUE TITLE
V2: I wanna boast my victory, but where's the proof?

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#47]
With the successful completion of the first two weeks and the amazing progress we've had, it's time to scale things up: allowing the storing of Room Results. We may not be able to integrate this part into GrepIt-Frontend within the duration of OpenCode '23, but we can still have a working backend!

As knowledge-seekers gain more knowledge and progress their way through the Realms of Quizventure, they see that their success rates have grown exponentially. Being the boastful seekers they are, they wish to share their results with others.
This would mean that we have to **store the User's results** for **each quiz**, in a room. Ofcourse, this would require **ALOT** of changes in the schema as well.
We would have a `results` array for each User, which would store the past results of the quizzes.
How would each result look like?
Each `result` would contain atleast the following:
```
1. User
2. questions[] (would contain the Questions for a specific Quiz in that Room)
3. options[] (would contain the Options marked by the User)
4. score (for these set of questions, basically score for a particular quiz in a room)
5. Room
```
The logic behind this schema is: We're storing the Options marked by the User, so that we can display in the frontend the set of correctly answered Questions and incorrectly answered Questions (since each Option has a isCorrect boolean field). We also have to store the Questions, to display those questions which aren't answered by the User.
We would also be required to remove the `onDelete: Cascade` attributes for `Option` and `Question` models.

The workflow would be as follows: when a new quiz is started by the creator, a **new result record** is created for **all the Users in that room**, and this record be updated in the `results` array for that User. The result record would contain the Questions for that quiz. 

Since this requires quite a lot of changes in the schema and the controllers in V2, if you've got any other optimised database design, feel free to recommend them.
**Note: Make the PR to the v2 branch of this repo**. Good Luck!

**Comment by WadadParker** [comment]
claim

**Comment by Jarviss77** [comment]
Claim

**Comment by WadadParker** [comment]
@VatsalBhuva11 We had discussed this in discord last week, can I be assigned this issue instead of room code one?

**Comment by VatsalBhuva11** [comment]
okay, assigning this to @WadadParker and unassigning him from #42 as this issue was partly discussed in an open discord thread.

**Comment by VatsalBhuva11** [comment]
@WadadParker status?

**Comment by WadadParker** [comment]
> @WadadParker status?

Will show you ss of schema and get this done by evening
