### ISSUE TITLE
Codebase Changes!!

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#51]
With active renovation going on in the Quizventure realms, the Mayor has decided to rebuild all the homes of the knowledge-seekers that reside in the realms. That, is a lot of effort!
But what are the changes?
Well, in v2, since we're not going to be deleting rooms, and giving the User the option to view their past results, we had to craft some new Schemas (called `Quiz`, and `Result`) (see #47 and #50 for more details). 
However, in v1, we had a temporary nature of rooms, and so we didn't really store a Quiz as such (but now, we're going to store the **result of each User for each Quiz**)

Hence, the following changes are required:
- updating the schemas to ensure that they use Quiz and Result schemas wherever needed (like removing the `questions[]` field and using Quiz instead in the `room` model, etc.)
- it is also required to make each Quiz unique to each Room (by updating the Quiz schema to have a Room field)
- any other schema changes to conform to v2, where the Room's nature is not temporary (i.e., gets permanently stored in the DB)

Since we're gonna have to change the main schema of our codebase (`Room`), this would require changes in certain controllers and socket-event handlers as well. These changes should be done in accordance with the new schema changes.

Since this is quite a big task, it is kept **open-for-all**. All the PRs that help in some contribution towards these codebase changes will earn points (depends on how big of a contribution you make to the changes.)

**NOTE: Before starting work after updating the schema, please get the schema confirmed once with me. A good schema will be allowed to be pushed, and other's will have to pull that (`npx prisma db pull`) and continue work on that **

Minimum points for each good PR: 5
Maximum points: 50

**Comment by TheDivineAurora** [comment]
claim

**Comment by VatsalBhuva11** [comment]
it is a open-for-all task, you dont need to claim it. just work on it and make the changes as required by the task

**Comment by VatsalBhuva11** [comment]
Note: you have a time 2 days for this task

**Comment by VatsalBhuva11** [comment]
please pull the updated schema using `git pull origin v2`.
