### ISSUE TITLE
Codebase Migration - I

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#52]
With the new schema set for the v2 branch (get the DB URL for v2 from #announcements in GrepIt-Backend channel in discord) and active renovation going on in the Quizventure realms, we are faced with some critical issues which will be handled individually. The main changes in the schema involve a new `Quiz` Schema and `Result` Schema. With the creation of each new quiz in a room, we will create a new record for that Quiz and add it to the corresponding Room's record, so that the Users can view their results later.

This task requires you to pull the latest changes from the `v2` branch of GrepIt-Backend, and make changes to:
1) startQuiz controller : 
- create a new Quiz record when this controller is executed. 
- create a new Result for each user connected in the room, for that particular quiz.

2) create a new `room.routes.js` file in `routes/v2`, add the `/startQuiz` route to this, and update the `v2-main.js` file accordingly.

3) attach screenshots in your PR which shows the working of the updated controller. You are to show that a new Quiz record is created when a quiz is started, and a new Result record was created for each user who participated in a Quiz. accordingly update the `API_ENDPOINTS.md` file (do not remove the response of the `v1's startQuiz`. add the response of the new controller, and mention that it is of v2.

**Comment by Jarviss77** [comment]
Claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
@Jarviss77 assigned to you
