### ISSUE TITLE
Codebase Migration - II

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#54]
With the `Result` record being successfully created for each user in that room when a new quiz starts, it's time to actually make use of it.
Once the last question of that quiz is displayed, we have to update the record of that User using suitable information. These changes should be made in the `startQuiz` controller, and should update the points of all the Users connected to that room in their respective `Result` record created.
The `points` can be obtained from the `User` model's `points` attribute, as every answer to a question is handled by sockets to update the points in real-time.

You are required to attach screenshots of this, showing that the points are actually getting updated in the DB when the quiz ends (by emulating the quiz through the template HTML files.) If you are not able to emulate the quiz due to changes required in any other controllers, please let me know.

Make the PR to the `v2` branch.

**Comment by Jarviss77** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by VatsalBhuva11** [comment]
assigned to @Jarviss77 !

**Comment by Apoorv012** [comment]
claim
