### ISSUE TITLE
Creater's Arsenal of Questions

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Backend#6]
Users embark on a journey through the grand Gateway, venturing into the heart of the quiz realm as they successfully log in.

**Task:**
Implement a controller to add multiple-choice questions (single correct) to the quiz realm. Create this controller in src/controllers/question.controllers.js. Establish a route to guide users in submitting their captivating questions (/api/v1/questions/add).

**Details:**
_Controller:_
Create a controller function, let's call it addMultipleChoiceQuestion, responsible for adding multiple-choice questions to the database.

_Route:_
Configure a route in src/routes/questions.routes.js to handle the user's request for adding questions. The route should be accessible through a POST request to /api/v1/questions/add.

_Request Body:_
Design the expected request body for adding a question. It should include the following fields:

question: The text of the question.
options: An array of option objects, each containing:
option: The text of the option.
isCorrect: A boolean indicating whether this option is correct.

_Validation:_
Validate the incoming request body to ensure it adheres to the expected structure. Provide meaningful error messages for any validation failures.

_Database Interaction:_
Interact with the database models (Question, Option) to store the new question and its options. Ensure proper association between questions and options. Make sure that number of options can be dynamic.

_Response:_
Respond with appropriate status codes and messages. This message will be displayed to the user as an alert so send appropriate message.

Claim this Issue and I would be happy if you give our repo a star.
We will be going to implement cool things like web-sockets so, stay tuned till then.
Ping me on discord if there's any confusion or require some resources

**Comment by WadadParker** [comment]
claim

**Comment by Jarviss77** [comment]
Claim

**Comment by bhupesh98** [comment]
@WadadParker Assigning you, but now you can't further ask for claiming the issue as you are reaching the limit of 3 assigned issue at any moment of time in Opencode'23.

**Comment by rnavaneeth992** [comment]
claim

**Comment by coderatiiita** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@WadadParker how's it going? if you need any help, feel free to ask here or on discord by pinging either me or Bhupesh

**Comment by WadadParker** [comment]
> @WadadParker how's it going? if you need any help, feel free to ask here or on discord by pinging either me or Bhupesh

Sure thank you so much, i'll raise the PR at night for review
