### ISSUE TITLE
Quiz Room Creation Magic

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#7]
HO HO HO! The user has now stepped into this mystical realm which feels surreal. A bunch of similar people wandering about in this realm, each requiring their own privacy.

This is where we'll be allowing the users to **create a Room**. 

Well, but how do you know who created the room? Middlewares! Create an appropriate `userAuth.middleware.js`, that will **verify and extract** a JWT sent from the frontend in a header "authorization". Use the extracted JWT to get the userId, and set the req.user object to contain the name, userId. This would allow you to identify the logged in user and secure routes that require authentication

Also, this would mean that the user that creates the room may (intuitively) gain extra privileges in that room, which may be discussed later. Hence, an **isCreator** field is required to know whether a user is a creator of that room or not. Consider updating the Prisma schema by adding a **isCreator** field in the **User model**, set to **False by default**. Do not create a migration. Get the schema verified, and if done well, can be pushed directly by running `npx prisma db push`

A Create Room button on the frontend, when clicked, will generate a random string that will serve as a code for that room. The frontend will pass this code as a **query parameter**, to the `/api/v1/room/create` route in the `src/routes/v1/room.routes.js` file, allowing the underlying services running the realm to capture this request and consequently create a room in the database, ensuring all relations are satisfied and the necessary fields are correctly filled (the User can be obtained from req.user)

Currently, there is a "test" user in the DB, with a "test" password. Create a new room by the user "test", and upload a screenshot of the received JSON Response. Update the routes wherever required, and ensure that the `room/create` route is protected and lets only authenticated users create rooms.

Please make sure that errors are handled everywhere promptly.

**Comment by Apoorv012** [comment]
claim

**Comment by QuantTitan** [comment]
claim

**Comment by optimus-pride** [comment]
Claim

**Comment by Jarviss77** [comment]
claim

**Comment by amanrubey** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@criticic assigned

**Comment by bhupesh98** [comment]
@criticic As we checked, you are already assigned with a issue from this repo. I really appreciate your determination and pro-active nature, but in this repo I am enforcing this rule as I think other contributors should also get the chance while you are working on a issue. Hope you understand and will soon create a PR for that assigned issue.

Unassigning @criticic . And this issue is again re-opened for the claim. Next claim message will get the issue assigneed.

**Comment by Apoorv012** [comment]
claim

**Comment by bhupesh98** [comment]
Assigning @Apoorv012

**Comment by rnavaneeth992** [comment]
claim

**Comment by coderatiiita** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@Apoorv012 there's quite a lot of things to be done in this issue. If you get confused by anything, feel free to reach out!

**Comment by VatsalBhuva11** [comment]
Everything done as required. Good job!
