### ISSUE TITLE
Room Personalization Ritual

### ISSUE THREAD

**Issue by VatsalBhuva11** [opencodeiiita/GrepIt-Backend#9]
Empowered by the quest for user autonomy, wizards unveil the Room Personalization Ritual. With the need of an **updated schema** and a **magical controller**, room creators can now **add names** and **optional descriptions** to their realms (rooms). They have the ability to shape the identity of their quiz room, making it uniquely theirs.

Identify the necessary changes that need to be made in the schema. Get the changes verified by either @VatsalBhuva11 or @bhupesh98 , before `npx prisma db push`.

Some unknown entity joined your personalized room? Gotta remove them! The creator should have the option to remove a User from the room. The controller for it may have the `userId` obtained as a `query parameter` to the `api/v1/room/user/delete` route. Update the routes wherever necessary, ensuring they make logical sense as to which file they're placed in (make it modular). The controller can be writen in the `src/controllers/room.controllers.js` file.

For testing, create a new room (from a 'test2' account), give it a name of `test2`, description of `test2`, create and add multiple users to this room using `npx prisma studio`, and using the `test2` account, delete some users from the room. Attach suitable screenshots.

Ensure that authentication middleware is used wherever required.

**Comment by criticic** [comment]
claim

**Comment by kushal7201** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by AngadManroy** [comment]
Claim

**Comment by PranavBansal21** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@criticic assigned to you.

**Comment by VatsalBhuva11** [comment]
Good job, @criticic !
